### ISSUE TITLE
aligning '=' in guards

### ISSUE THREAD

**Issue by iTsluku** [alx741/vim-hindent#14]
Hey, should vim-hindent be able to align those two '=' in the guards of the function (line 13 and 14) ? (doesn't align it for me when saving the file -- i did :HindentEnable and hindent works)

11 minAndMax ⦂ Integer → Integer → (Integer, Integer)
12 minAndMax x y
13   | x >= y = (y, x)
14   | otherwise = (x, y)

**Comment by alx741** [comment]
Hey, I don't think [hindent does that](https://github.com/mihaimaruseac/hindent/blob/master/TESTS.md#function-declarations)

**Comment by iTsluku** [comment]
alright thanks - thought that's a thing somehow.
