### ISSUE TITLE
Range-awareness causes cursor teleport

### ISSUE THREAD

**Issue by pikajude** [alx741/vim-hindent#9]
Related to https://github.com/alx741/vim-hindent/issues/7. Now that every hindent invocation is range-aware, the cursor is moved to the beginning of the selection after the command is run. Thus if I'm formatting an entire file, my cursor will jump to (0,0) afterwards which is very annoying.

**Comment by alx741** [comment]
Thanks for the report! it should be fixed now, please check it out

**Comment by pikajude** [comment]
Works great, thanks for quick fix.
